version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - payment_network

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - payment_network

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - payment_network

  adminer:
    image: adminer:latest
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - db
    networks:
      - payment_network

volumes:
  postgres_data:
  redis_data:

networks:
  payment_network:
    driver: bridge 